build: Add -lm to tests
Since the introduction of igt_stats and its usage in gem_exec_nop, we
need to link the tests against libm. My rebasing bot complained when
linking gem_exec_nop:

  lib/igt_stats.c:492: undefined reference to `sqrt'

Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>